// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['config']['App']['OnSecondInstanceLaunch'](arg1);
}
