// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCollectionsTree() {
  return window['go']['services']['DashboardService']['GetCollectionsTree']();
}

export function GetUserConfigDir() {
  return window['go']['services']['DashboardService']['GetUserConfigDir']();
}

export function IsFirstLaunch() {
  return window['go']['services']['DashboardService']['IsFirstLaunch']();
}

export function LoadDashboardData() {
  return window['go']['services']['DashboardService']['LoadDashboardData']();
}

export function SetFirstLaunchDone() {
  return window['go']['services']['DashboardService']['SetFirstLaunchDone']();
}
