// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetCollectionsTree():Promise<models.CollectionsTree>;

export function GetUserConfigDir():Promise<string>;

export function IsFirstLaunch():Promise<boolean>;

export function LoadDashboardData():Promise<models.DashboardData>;

export function SetFirstLaunchDone():Promise<boolean>;
